### ISSUE TITLE
Not a bug, just wanted to suggest! (Long)

### ISSUE THREAD

**Issue by Jely710** [Draylar/identity#130]
Comments are disabled, so I'm not sure where else to put these - delete this if it's wrong or something.

I first want to say, that this is a great mod! I understand that it takes a  long while to develop, but I wanted to suggest a few things.

Firstly, you should probably increase the mining range for some morphs. Bigger mobs aren't even able to mine at all!

Next up, abilities! I'm trying to make a unique one for each mob. They differ in usefulness.

- Armor Stand - Press R to go into "sneak mode". Mobs have a low detection range for you, and you are made slower. It's toggleable.
- Bat - Press R to give nearby mobs the Glowing effect, as a sort of "Echolocation". Has a medium cooldown.
- Bee - You can hide in beehives by left-clicking on them. Your viewpoint is changed to be where the beehive is facing, and you get a pumpkin-like overlay with a few holes to see out of. Crouch to exit.
- Blaze - Fire and Lava slowly heals you
- Cat - Speed!
- Cave Spider - Press R to make your next attack give Poison. Has a long cooldown. You are also immune to Cobwebs.
- Chicken - Press R to lay an egg. Has a long cooldown, it's mainly for fun.
- Cod - Safety in numbers! Being around other cod makes mobs ignore you.
- Cow - Press R to get a milk-like effect. Do you drink your own milk? Has a long cooldown.
- Creeper - it already has one.
- Dolphin - First off, you have air bars for both water AND land. Also, you can jump out of the water and go really high up.
- Donkey - Press R for a temporary speed boost. Has a medium cooldown.
- Drowned - Press R to throw a trident! This trident is weaker than a normal one. Has a medium cooldown.
- Elder Guardian - Press R to shoot a laser at the mob you hit. Also, they can breath in air, but are constantly jumping.
- Ender Dragon - End Crystals heal you.
- Enderman - Mobs avoid looking at you, but if they to happen to look at your face, you gain a temporary strength boost.
- Endermite - Press R to have a chorus-fruit like effect. Endermen are also immediately angry at you.
- Evoker - Press R to summon a line of Evocation Fangs in front of you. Has a long cooldown.\
- Fox - Press R to sleep. This skips to either nighttime or daytime, depending on what time you sleep at. Has a cooldown until the next day.
- Ghast - I can't think of a new one.
- Giant - Any mobs you walk on get damaged immensely.
- Guardian - Same as Elder Guardian, just weaker.
- Hoglin - Press R to launch any nearby mobs up into the air. Has a medium cooldown.
- Horse - Same as Donkey, but a bit stronger.
- Husk - Immunity to cacti.
- Illusioner - Press R to make a copy of you like an Illusioner. This distracts mobs, and disappears after a while. Has a long cooldown.
- Iron Golem - Same as Hoglin. You also naturally deal more knockback.
- Llama - Press R to spit. Has a short cooldown.
- Magma Cube - You can't move, and have to jump to go anywhere. Press R to gain temporary jump boost.
- Mule - Same as Donkey. In-between Horse and Donkey.
- Mooshroom - Same as Cow.
- Ocelot - Same as Cat.
- Panda - Press R to roll. You go pretty quickly forward. Has a medium cooldown.
- Parrot - You do the same thing as parrots normally, replicating nearby mob's noises.
- Phantom - Crashing into mobs deals damage.
- Pig - pigs are useless.
- Piglin - Piglins are Passive, but Brutes are neutral..
- Brute - Piglins and Brutes are both passive.
- Pillager - You basically have Infinity on all bows/crossbows.
- Polar Bear - Press R to do a strengthened attack. It has a medium cooldown.
- Pufferfish - Press R to puff up. You poison and damage any nearby mobs. Has a short cooldown.
- Rabbit - Press R to get temporary (small) jump boost. Has a short cooldown.
- Ravager - Press R to bite at your opponents, like a Ravager does. This knocks them far back, and does big damage. Has a medium cooldown.
- Salmon - Same as Cod.
- Sheep - Press R to eat any grass block you may be standing on. This replenishes your hunger as much as steak. Has a medium cooldown.
- Shulker - Press R to open your shell and shoot a Shulker Bullet, which goes for the nearest mob and gives them levitation. Has a long cooldown.
- Silverfish - Same thing as Bee, but with stone blocks. You can't see while in blocks, though.
- Skeleton - You have infinite Arrows, and a decreased bow use time.
- Skeleton Horse - Same as Horse. You can also breath underwater.
- Slime - Same as Magma Cube.
- Snow Golem - You leave a trail of snow behind you.
- Spider - You are immune to Cobwebs.
- Squid - First off, you actually look where you swim. Secondly, press R to shoot Ink. This blinds those it hits and makes them wander randomly for a short while.
- Stray - Same as Skeleton, but with Slowness Arrows.
- Strider - You are slowed on land.
- Trader Llama - Same as Llama.
- Tropical Fish - Same as Cod.
- Turtle - You have more natural defense. You are also slower on land. Press R to go in your shell, making you immune to all damage but also unable to do anything. Toggleable.
- Vex - You can pass through blocks, like in Spectator Mode.
- Villager - Villager Trades are decreased.
- Vindicator - Extra damage with Iron Axes.
- Wandering Trader - Same as Villager.
- Witch - Press R to throw a random Poison, Damage, or Slowness potion. Has a long cooldown.
- Wither - Everything runs from you.
- Wither Skeleton - Press R to make your next attack give the Wither effect. Has a medium cooldown.
- Wolf - Press R to Howl, summoning some wolves off-screen that help you fight. They leave once all opponents are defeated. Has a long cooldown.
- Zoglin - Same as Hoglin.
- Zombie - Same as Wolf, but it summons Zombies.
- Zombie Horse - Same as Horse.
- Zombie Villager - Nothing special.
- Zombified Piglin - Any nearby Zombified Piglins attack whatever attacks you.

That's all of them! You don't need to do them all, I just wanted to share some ideas I had.

**Comment by Draylar** [comment]
Thanks for the huge idealist, much appreciated!

I just implemented the *Cow*, *Witch* and *Endermite* abilities as you described them here. This will be out in the next update.

**Comment by James103** [comment]
The [wiki page](https://github.com/Draylar/identity/wiki/Abilities) still needs to be updated to account for the new abilities (Cow, Witch, Endermite, Llama).

**Comment by Jely710** [comment]
:D

**Comment by jloqfjgk** [comment]
> Spider - You are immune to Cobwebs.

This also applies to cave spider.

Currently, cave spider identity will still experience slow movement through a cobweb.

I hope this feature will be implemented in the future.
